### ISSUE TITLE
Dropdown issue

### ISSUE THREAD

**Issue by ashutoshsenger** [antew7/number-system#14] opened 2018-10-02 14:57 UTC
When i'm doing hover on dropdown buttons after scrolling down the screen the dropdown-content div goes downward by some pixels.
![screenshot from 2018-10-02 20-23-39](https://user-images.githubusercontent.com/31319848/46357000-80df5180-c681-11e8-9473-febe2170dac4.png)

**Comment by akim8** [comment] 2018-10-02 17:28
duplicate of #13

**Comment by antew7** [comment] 2018-10-03 04:08
@ashutoshsenger please refer to #13 and yes please check creating a issue whether the issue is present or not.
closing this issue for now :)

**Closed by antew7** 2018-10-03 04:08 UTC
